#
# Copyright (C) 2018 The Xiaomi-SDM660 Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# This file sets variables that control the way modules are built
# thorughout the system. It should not be used to conditionally
# disable makefiles (the proper mechanism to control what gets
# included in a build is to use PRODUCT_PACKAGES in a product
# definition file).
#

# This file is generated by device/xiaomi/jasmine_sprout/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/xiaomi/jasmine_sprout/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/xiaomi/jasmine_sprout/proprietary/bin/wfdservice:system/bin/wfdservice \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/init/wfdservice.rc:system/etc/init/wfdservice.rc \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/calib.cfg:system/etc/calib.cfg \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/init/dpmd.rc:system/etc/init/dpmd.rc \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml:system/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml:system/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/com.qualcomm.qti.imscmservice.xml:system/etc/permissions/com.qualcomm.qti.imscmservice.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/com.qti.snapdragon.sdk.display.xml:system/etc/permissions/com.qti.snapdragon.sdk.display.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/embms.xml:system/etc/permissions/embms.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/wfdconfig.xml:system/etc/wfdconfig.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/etc/wfdconfigsink.xml:system/etc/wfdconfigsink.xml \
    vendor/xiaomi/jasmine_sprout/proprietary/firmware/goodixfp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b00 \
    vendor/xiaomi/jasmine_sprout/proprietary/firmware/goodixfp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b01 \
    vendor/xiaomi/jasmine_sprout/proprietary/firmware/goodixfp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b02 \
    vendor/xiaomi/jasmine_sprout/proprietary/firmware/goodixfp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b03 \
    vendor/xiaomi/jasmine_sprout/proprietary/firmware/goodixfp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b04 \
    vendor/xiaomi/jasmine_sprout/proprietary/firmware/goodixfp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b05 \
    vendor/xiaomi/jasmine_sprout/proprietary/firmware/goodixfp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b06 \
    vendor/xiaomi/jasmine_sprout/proprietary/firmware/goodixfp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b07 \
    vendor/xiaomi/jasmine_sprout/proprietary/firmware/goodixfp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.mdt \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.qualcomm.qti.imscmservice-V2.0-java.jar:system/framework/com.qualcomm.qti.imscmservice-V2.0-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.qualcomm.qti.imscmservice-V2.1-java.jar:system/framework/com.qualcomm.qti.imscmservice-V2.1-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.qualcomm.qti.uceservice-V2.0-java.jar:system/framework/com.qualcomm.qti.uceservice-V2.0-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.quicinc.cne.api-V1.0-java.jar:system/framework/com.quicinc.cne.api-V1.0-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.quicinc.cne.api-V1.1-java.jar:system/framework/com.quicinc.cne.api-V1.1-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.quicinc.cne.constants-V1.0-java.jar:system/framework/com.quicinc.cne.constants-V1.0-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.quicinc.cne.constants-V2.0-java.jar:system/framework/com.quicinc.cne.constants-V2.0-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.quicinc.cne.constants-V2.1-java.jar:system/framework/com.quicinc.cne.constants-V2.1-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.quicinc.cne.server-V1.0-java.jar:system/framework/com.quicinc.cne.server-V1.0-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.quicinc.cne.server-V2.0-java.jar:system/framework/com.quicinc.cne.server-V2.0-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.quicinc.cne.server-V2.1-java.jar:system/framework/com.quicinc.cne.server-V2.1-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/com.quicinc.cne.server-V2.2-java.jar:system/framework/com.quicinc.cne.server-V2.2-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/audiosphere.jar:system/framework/audiosphere.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/embmslibrary.jar:system/framework/embmslibrary.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/vendor.qti.data.factory-V1.0-java.jar:system/framework/vendor.qti.data.factory-V1.0-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar:system/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/vendor.qti.ims.callinfo-V1.0-java.jar:system/framework/vendor.qti.ims.callinfo-V1.0-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/framework/vendor.qti.ims.rcsconfig-V1.0-java.jar:system/framework/vendor.qti.ims.rcsconfig-V1.0-java.jar \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/com.qualcomm.qti.imscmservice@1.0.so:system/lib/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/com.qualcomm.qti.wifidisplayhal@1.0.so:system/lib/com.qualcomm.qti.wifidisplayhal@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/extractors/libmmparser.so:system/lib/extractors/libmmparser.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/fm_helium.so:system/lib/fm_helium.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/lib-imscamera.so:system/lib/lib-imscamera.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/lib-imsvideocodec.so:system/lib/lib-imsvideocodec.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/lib-imsvtextutils.so:system/lib/lib-imsvtextutils.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/lib-imsvtutils.so:system/lib/lib-imsvtutils.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libFileMux.so:system/lib/libFileMux.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libOmxMux.so:system/lib/libOmxMux.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libGPTEE_system.so:system/lib/libGPTEE_system.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libQTEEConnector_system.so:system/lib/libQTEEConnector_system.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libdpmctmgr.so:system/lib/libdpmctmgr.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libdpmfdmgr.so:system/lib/libdpmfdmgr.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libdpmframework.so:system/lib/libdpmframework.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libdpmtcm.so:system/lib/libdpmtcm.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libfm-hci.so:system/lib/libfm-hci.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libimscamera_jni.so:system/lib/libimscamera_jni.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libimsmedia_jni.so:system/lib/libimsmedia_jni.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libmmparser_lite.so:system/lib/libmmparser_lite.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libmmrtpdecoder.so:system/lib/libmmrtpdecoder.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libmmrtpencoder.so:system/lib/libmmrtpencoder.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/librcc.so:system/lib/librcc.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/liblistenjni.so:system/lib/liblistenjni.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/liblistensoundmodel2.so:system/lib/liblistensoundmodel2.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libsd_sdk_display.so:system/lib/libsd_sdk_display.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libsdm-disp-apis.so:system/lib/libsdm-disp-apis.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfdclient.so:system/lib/libwfdclient.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfdnative.so:system/lib/libwfdnative.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfdavenhancements.so:system/lib/libwfdavenhancements.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfdcodecv4l2.so:system/lib/libwfdcodecv4l2.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfdcommonutils.so:system/lib/libwfdcommonutils.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfdconfigutils.so:system/lib/libwfdconfigutils.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfdmminterface.so:system/lib/libwfdmminterface.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfdmmsink.so:system/lib/libwfdmmsink.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfdmmsrc.so:system/lib/libwfdmmsrc.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfdrtsp.so:system/lib/libwfdrtsp.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfdservice.so:system/lib/libwfdservice.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfdsm.so:system/lib/libwfdsm.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfduibcinterface.so:system/lib/libwfduibcinterface.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfduibcsink.so:system/lib/libwfduibcsink.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfduibcsinkinterface.so:system/lib/libwfduibcsinkinterface.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfduibcsrc.so:system/lib/libwfduibcsrc.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/libwfduibcsrcinterface.so:system/lib/libwfduibcsrcinterface.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/vendor.display.color@1.0.so:system/lib/vendor.display.color@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/vendor.display.color@1.1.so:system/lib/vendor.display.color@1.1.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/vendor.display.color@1.2.so:system/lib/vendor.display.color@1.2.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/vendor.display.postproc@1.0.so:system/lib/vendor.display.postproc@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/vendor.qti.esepowermanager@1.0.so:system/lib/vendor.qti.esepowermanager@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/vendor.qti.hardware.factory@1.0.so:system/lib/vendor.qti.hardware.factory@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/vendor.qti.hardware.qdutils_disp@1.0.so:system/lib/vendor.qti.hardware.qdutils_disp@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/vendor.qti.hardware.qteeconnector@1.0.so:system/lib/vendor.qti.hardware.qteeconnector@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/vendor.qti.hardware.tui_comm@1.0.so:system/lib/vendor.qti.hardware.tui_comm@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/vendor.qti.hardware.vpp@1.1.so:system/lib/vendor.qti.hardware.vpp@1.1.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib/vendor.qti.imsrtpservice@1.0.so:system/lib/vendor.qti.imsrtpservice@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/fm_helium.so:system/lib64/fm_helium.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/lib-imscamera.so:system/lib64/lib-imscamera.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/extractors/libmmparser.so:system/lib64/extractors/libmmparser.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/lib-imsvideocodec.so:system/lib64/lib-imsvideocodec.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/lib-imsvt.so:system/lib64/lib-imsvt.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/lib-imsvtextutils.so:system/lib64/lib-imsvtextutils.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/lib-imsvtutils.so:system/lib64/lib-imsvtutils.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libFileMux.so:system/lib64/libFileMux.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libOmxMux.so:system/lib64/libOmxMux.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libGPTEE_system.so:system/lib64/libGPTEE_system.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libQTEEConnector_system.so:system/lib64/libQTEEConnector_system.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libdpmctmgr.so:system/lib64/libdpmctmgr.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libdpmfdmgr.so:system/lib64/libdpmfdmgr.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libdpmframework.so:system/lib64/libdpmframework.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libfm-hci.so:system/lib64/libfm-hci.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libdpmtcm.so:system/lib64/libdpmtcm.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libmmosal.so:system/lib64/libmmosal.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libmmparser_lite.so:system/lib64/libmmparser_lite.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libmmrtpdecoder.so:system/lib64/libmmrtpdecoder.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libmmrtpencoder.so:system/lib64/libmmrtpencoder.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/librcc.so:system/lib64/librcc.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/liblistenjni.so:system/lib64/liblistenjni.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/liblistensoundmodel2.so:system/lib64/liblistensoundmodel2.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libsd_sdk_display.so:system/lib64/libsd_sdk_display.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libsdm-disp-apis.so:system/lib64/libsdm-disp-apis.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libwfdclient.so:system/lib64/libwfdclient.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/libwfdnative.so:system/lib64/libwfdnative.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/vendor.display.color@1.0.so:system/lib64/vendor.display.color@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/vendor.display.color@1.1.so:system/lib64/vendor.display.color@1.1.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/vendor.display.color@1.2.so:system/lib64/vendor.display.color@1.2.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/vendor.display.postproc@1.0.so:system/lib64/vendor.display.postproc@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/vendor.qti.esepowermanager@1.0.so:system/lib64/vendor.qti.esepowermanager@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/vendor.qti.hardware.factory@1.0.so:system/lib64/vendor.qti.hardware.factory@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/vendor.qti.hardware.qdutils_disp@1.0.so:system/lib64/vendor.qti.hardware.qdutils_disp@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/vendor.qti.hardware.qteeconnector@1.0.so:system/lib64/vendor.qti.hardware.qteeconnector@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/vendor.qti.hardware.tui_comm@1.0.so:system/lib64/vendor.qti.hardware.tui_comm@1.0.so \
    vendor/xiaomi/jasmine_sprout/proprietary/lib64/vendor.qti.hardware.vpp@1.1.so:system/lib64/vendor.qti.hardware.vpp@1.1.so 

PRODUCT_PACKAGES += \
    QtiSystemService \
    QtiTelephonyService \
    WfdService \
    WfdCommon \
    chargeonlymode
